name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        mode: [debug, release]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -mode ${{ matrix.mode }}
    - if: runner.os == 'Linux'
      run: luamake lua test/glibc-version.lua
